### ISSUE TITLE
Permission issue when using docker-compose.yml

### ISSUE THREAD

**Issue by grimsi** [BrunoTh/GarrysModDocker#2]
When using the provided docker-compose.yml the server can't install addons from the configured collection. Instead the following error messages will be logged:

>Processing addon 88: ULX (557962280)...
   Failed to open .gma, redownloading...
   Downloaded!
   Extracting...
FS:  Tried to Write NULL file handle!
FS:  Tried to Write NULL file handle!
FS:  Tried to Close NULL file handle!
FS:  Tried to Close NULL file handle!
   Mounted!

When starting the server afterwards it will start without addons and will log the following errors:
>Couldn't mount addon file 'cache/srcds/557962280.gma' from 'ULX' (557962280)
Not loading addon 'cache/srcds/1947794080.gma' - file doesn't exist

However starting via `docker run` works fine. I think it's a permission issue with the volumes and will investigate further. Any help is appreciated

**Comment by grimsi** [comment]
I was able to (sort of) fix it by setting the folder permissions on the volume folder to "777".
The default path for docker volumes is "/var/lib/docker/volumes/".
However I'm not really satisfied with this solution...

**Comment by BrunoTh** [comment]
Thank you for the feedback.
I just committed the fix for the issue.

The problem was that the mounted volumes had `root` as owner but the gmod server is running as `steam`. Before the server starts the ownership of the affected directories gets fixed now.

You can also do this manually INSIDE the docker container. You should never fiddle around with `/var/lib/docker` directly. Besides security issues this can cause some weird behavior.

Have a nice day!
